# Generated by Django 5.2.7 on 2025-11-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Отображать товар в каталоге', verbose_name='Опубликован'),
        ),
    ]
